# docker bake build this image as pre-requsite to be used here
FROM php_base_local AS php_base

# Install php extensions
RUN install-php-extensions pdo_mysql zip amqp opcache apcu pcntl curl sockets intl xdebug

# Activate Xdebug mode covera in php.ini
RUN echo "xdebug.mode=coverage" | tee -a "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"