# docker bake build this image as pre-requsite to be used here
FROM php_base_local AS php_base

# Install Chromium and ChromeDriver for Web Tests
RUN apk add --no-cache nss nss-tools chromium chromium-chromedriver
# Install PHP extensions
RUN install-php-extensions pdo_mysql zip opcache apcu redis http sockets soap